### ISSUE TITLE
BT-707 remove Restricted.

### ISSUE THREAD

**Issue by bjornjorgensen** [open-contracting-extensions/eforms#10]
Restricted. Is not in the list https://op.europa.eu/en/web/eu-vocabularies/concept-scheme/-/resource?uri=http://publications.europa.eu/resource/authority/communication-justification

**Comment by jpmckinney** [comment]
@odscjen The guidance either needs to require adding "Restricted. " as a prefix, or the example needs to omit "Restricted. "

Since `accessDetails` has wide semantics, I think a prefix is a good idea, and it can be made clearer as e.g. "Access is restricted. Reason: "

**Comment by jpmckinney** [comment]
cc @duncandewhurst

**Comment by odscjen** [comment]
"Restricted" has come from the mapping for BT-14
> [Get the document for the document reference](operations.md#get-the-document-for-a-document-reference).
        Set its `.documentType` to 'biddingDocuments' and set it's `.accessDetails` to "Restricted.".

So we don't need to add guidance about adding the prefix to BT-707, but we do need to add a note that if there's already text in `accessDetails` then BT-707 should append. I'll remove "Restricted from the BT-707 examples"
