### ISSUE TITLE
BT 63 allowed -> Allowed

### ISSUE THREAD

**Issue by bjornjorgensen** [open-contracting-extensions/eforms#11]
Change "variantPolicy": "allowed"
to
"variantPolicy": "Allowed"

**Comment by jpmckinney** [comment]
Hi @bjornjorgensen, the `Code` value from the [permissions.csv](https://extensions.open-contracting.org/en/extensions/submissionTerms/master/codelists/) codelist (that is linked from the BT-63 guidance) must be used ('allowed'), not the `Title` value ("Allowed").
