### ISSUE TITLE
Remove BT-747 

### ISSUE THREAD

**Issue by bjornjorgensen** [open-contracting-extensions/eforms#8]
Bt-747 was removed in https://github.com/open-contracting-extensions/eforms/commit/4ff185f5f68b9f77d18e40770136aa71e03172fc but there are a lot (6) of reference to it 
![image](https://github.com/user-attachments/assets/a80cda45-d1a7-4f5e-bff1-5d1219a7548b)

**Comment by jpmckinney** [comment]
Thanks - the guidance has been updated in 942bd75cf0a6a68ef150cfad577bee45b2470a8e
