### ISSUE TITLE
BT-771-Lot can -> may

### ISSUE THREAD

**Issue by bjornjorgensen** [open-contracting-extensions/eforms#9]
"late-all": "At the discretion of the buyer, all missing tenderer-related documents may be submitted later.",
"late-none": "No documents can be submitted later.",
"late-some": "At the discretion of the buyer, some missing tenderer-related documents may be submitted later.",

change "submissionMethodDetails": "All missing tenderer-related documents can be submitted later." to
"submissionMethodDetails": "At the discretion of the buyer, all missing tenderer-related documents may be submitted later."

**Comment by jpmckinney** [comment]
@odscjen In the example, use the verbatim label from the authority table (we only fix normative language in our own codelists, etc.).

**Comment by bjornjorgensen** [comment]
This is the link that I'm using https://op.europa.eu/en/web/eu-vocabularies/concept-scheme/-/resource?uri=http://publications.europa.eu/resource/authority/missing-info-submission

**Comment by jpmckinney** [comment]
cc @duncandewhurst

**Comment by odscjen** [comment]
The text that was in the example appears to be from an [older version of the codelist](https://op.europa.eu/en/web/eu-vocabularies/dataset/-/resource?uri=http://publications.europa.eu/resource/dataset/missing-info-submission&version=20220316-0). I'll update it
